# Generated by Django 5.2.10 on 2026-01-18 13:32

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('skills', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-crawled_at'], name='jobs_jobpos_crawled_94e1e3_idx')],
                'unique_together': {('source', 'source_id')},
            },
        ),
    ]
