# Generated by Django 5.2.10 on 2026-01-19 18:26

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_add_hnsw_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
