# Generated by Django 6.0.1 on 2026-01-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('parsed_conditions', models.JSONField(default=dict)),
                ('result_count', models.IntegerField(default=0)),
                ('search_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='search_sear_created_394ee2_idx')],
            },
        ),
    ]
